### ISSUE TITLE
Maiar Culture Bug

### ISSUE THREAD

**Issue by bedevere** [Rigmored/mod#11]
Noticed an issue with Sauron, as the game progresses, his personally owned territory become Maiar and does not switch back to orc.  This is problematic due to there being no buildings associated with the Maiar culture.  Ideally stopping Maiar culture from appearing in the first place would be the ideal fix.

**Comment by Glariamn** [comment]
It should be fixed. Should be disabled in the game rules but you can turn culture conversion on if you want

**Comment by bedevere** [comment]
So I went into the culture conversion code and excluded those with maiar culture.  I also excluded the dwarves/elves/numenor from the same.  Reason for this was the fix I made to colonization.
